закончила модуль 7
js-tasks-ru/jsbasic-20240219_balalum pull request #14
Opened 2024-04-02 16:33 UTC by MariaKochanova

2024-04-04 11:38 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-04 11:40 UTC, koalex requested changes
Нужно решить **8-1**. Без него не смогу принять ПР

2024-04-08 03:06 UTC, koalex requested changes
8-1

2024-05-20 10:51 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-05-20 10:54 UTC, MariaKochanova commented
Добрый день. Я решила 8-1, надеюсь она добавилась сюда

2024-05-20 12:47 UTC, koalex approved these changes

2024-05-20 12:48 UTC, merged